---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:


- project: cp4waiops-evtmgr
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Event Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-eventmanager
    kind: EventManagerDemoContent
    install: true



