apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: aiops
    app.kubernetes.io/managed-by: ibm-aiops-orchestrator
    app.kubernetes.io/name: custom-sized-profiles
    app.kubernetes.io/part-of: ibm-aiops
    aiops-custom-size-profile-version: 3.4.0-20220628
  name: aiops-custom-size-profile
data:
  # WARNING: Modifications to this ConfigMap may cause your AIOPs installation to become unstable.
  profiles: |
    generatedfor: NonHA
    automationbase:
      kafka:
        replicas: 1
        resources:
          requests:
            cpu: 269m
            memory: 1000Mi
          limits:
            cpu: 2000m
            memory: 2000Mi
        config:
          default.replication.factor: 1
          min.insync.replicas: 1
      elasticsearch:
        replicas: 1
        resources:
          requests:
            cpu: 1544m
            memory: 2977Mi
          limits:
            cpu: 4000m
            memory: 2977Mi
        env:
          - name: ES_JAVA_OPTS
            value: -Xms1488M -Xmx1488M 
        tlsproxy:
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
    cp4waiops-eventprocessor:
      flink:
        taskmanager:
          replicas: 2
          resources:
            requests:
              cpu: 3000m
              memory: 6000Mi
            limits:
              cpu: 6000m
              memory: 6000Mi
        properties:
          jobmanager.memory.heap.size: 200mb
          jobmanager.memory.jvm-metaspace.size: 100mb
          taskmanager.memory.heap.size: 2084mb
          taskmanager.memory.managed.size: 298mb
          taskmanager.numberOfTaskSlots: 8
    configmaps:
    - name: aiops-topology-sizing
      data:
        asm: |
          cassandra:
            specs:
              replicas: 1
            containers:
              cassandra:
                resources:
                  requests:
                    cpu: 1159m
                    memory: 6000Mi
                  limits:
                    cpu: 3000m
                    memory: 6000Mi
                env:
                  - name: CASSANDRA_HEAP_NEWSIZE
                    value: 720M 
                  - name: CASSANDRA_HEAP_SIZE
                    value: 3000M 
    operandconfigs:
    - name: couchdb
      spec:
        couchdbcluster:
          size: 1
          resources:
            db:
              requests:
                cpu: 985m
                memory: 1000Mi
              limits:
                cpu: 2000m
                memory: 1000Mi
    - name: ir-ai-operator
      spec:
        aiopsanalyticsorchestrator:
          customSizing:
            deployments:
            - name: metric-action
              replicas: 1
              containers:
              - name: metric-action
                requests:
                  cpu: 585m
                  memory: 1200Mi
                limits:
                  cpu: 2000m
                  memory: 1500Mi
            - name: metric-api
              replicas: 1
              containers:
              - name: metric-api
                requests:
                  cpu: 500m
                  memory: 1200Mi
                limits:
                  cpu: 1000m
                  memory: 1500Mi
            - name: metric-spark
              replicas: 1
              containers:
              - name: metric-spark
                requests:
                  cpu: 114m
                  memory: 1573Mi
                limits:
                  cpu: 1000m
                  memory: 1656Mi
            - name: spark-worker
              replicas: 2
              containers:
              - name: spark-worker
                requests:
                  cpu: 1077m
                  memory: 3000Mi
                limits:
                  cpu: 3000m
                  memory: 3750Mi
    - name: ir-core-operator
      spec:
        issueresolutioncore:
          customSizing:
            deployments:
            - name: rba-as
              replicas: 1
              containers:
              - name: rba-as
                requests:
                  cpu: 131m
                  memory: 200Mi
                limits:
                  cpu: 1000m
                  memory: 1000Mi
            - name: rba-rbs
              replicas: 1
              containers:
              - name: rba-rbs
                requests:
                  cpu: 152m
                  memory: 200Mi
                limits:
                  cpu: 1000m
                  memory: 1538Mi
    - name: ir-lifecycle-operator
      spec:
        lifecycleservice:
          customSizing:
            statefulSets:
            - name: eventprocessor-ep-taskmanager
              replicas: 1
              containers:
              - name: taskmanager
                requests:
                  cpu: 1129m
                  memory: 4000Mi
                limits:
                  cpu: 3000m
                  memory: 4000Mi
