---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:



- project: cp4waiops-infra
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Infrastructure Management
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-infrastructure-management
    kind: InfrastructureManagement
    install: true
    # Version of the catalog subscription
    subscription_channel: v3.4
    #subscription_channel: 3.4-dev
    # LDAP
    install_ldap: true
    # ldap domain
    ldap_domain: ibm.com
    # ldap base
    ldap_base: dc=ibm,dc=com
    # ldap admin password
    ldap_admin_password: P4ssw0rd!

# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS GLOBAL CONFIGURATION
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
storage_class_file: automatic
#storage_class_file: ibmc-file-gold-gid               # ROKS
#storage_class_file: ocs-storagecluster-cephfs        # ODF
#storage_class_file: ibmc-vpc-block-10iops-tier       # IBM VPC
#storage_class_file: rook-cephfs                      # FYRE
#storage_class_file: nfs-client                       # TEC
storage_class_block: automatic
#storage_class_block: ibmc-block-gold                 # ROKS
#storage_class_block: ocs-storagecluster-ceph-rbd     # ODF
#storage_class_block: ibmc-vpc-block-10iops-tier      # IBM VPC
#storage_class_block: rook-cephfs                     # FYRE
#storage_class_block: nfs-client                      # TEC



# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Pull Registires
# --------------------------------------------------------------------------------------------------------------------------------------
entitled_registry: cp.icr.io
entitled_registry_user: cp
catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
ocp_major_version: automatic

