#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#       __________  __ ___       _____    ________            
#      / ____/ __ \/ // / |     / /   |  /  _/ __ \____  _____
#     / /   / /_/ / // /| | /| / / /| |  / // / / / __ \/ ___/
#    / /___/ ____/__  __/ |/ |/ / ___ |_/ // /_/ / /_/ (__  ) 
#    \____/_/      /_/  |__/|__/_/  |_/___/\____/ .___/____/  
#                                              /_/            
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------------------------------------"
#  Installing CP4WAIOPS
#
#  CloudPak for Watson AIOps
#
#  ©2022 nikh@ch.ibm.com
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# Installs:
#
#  - IBM Operator
#  - AI Manager
#  - Demo Content
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
# ---------------------------------------------------------------------------------------------------------------------------------------------------"
 

- hosts: localhost
  #become: true
  #vars_files: {{ config_file }}
  #vars_files: ./configs/cp4waiops-roks-all.yaml

  tasks:
  - name: 🚀 MAIN INSTALLATION LOOP - Install Modules
    debug: 
      msg: 
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "                                                                                                                                                   "
      - "       🚀 CloudPak for Watson AIOps - INSTALLATION - AI Manager and Demo Content                                                            "
      - "                                                                                                                                                   "
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"
      - "***************************************************************************************************************************************************"

  - name: 🛠️  Config File Path
    set_fact: config_file_path="./configs/cp4waiops-roks-aimanager-all.yaml"


  - name: 🛠️  Show Global Config
    debug:
      var: config_file_path

  - name: 🛠️  Ansible check config file exists
    stat:
      path: "{{config_file_path}}"
    register: p
  - debug:
      msg: "  ✅ Config File exists..."
    when: p.stat.exists
  - fail: msg="The specified config file {{config_file_path}} does not exist"
    when: p.stat.exists == False
      
  - name: 🛠️  Import Config File
    include_vars:
      file: "{{config_file_path}}"
      name: config_file

  - name: 🛠️  Show Global Config
    debug:
      var: config_file





  # Loop over all Clusters
  - name: ♻️  Deploy Cloud Pak for Watson AIOps Assets - Loop over Clusters
    include_role:
      name: cp4waiops-install
    loop: "{{ config_file.cp4waiops | default([]) }}"
    loop_control:
      loop_var: current_cp4waiops_cluster

